language: python

python:
  - "2.7"

install: "pip install -r dev-requirements.txt"

script:
  - flake8 --max-line-length=240 .
  - coverage run --source=. -m unittest discover

after_success:
  - pip install python-coveralls
  - coveralls
